[package]
name = "nikkepwned"
version = "5.0.12"
description = "Password Manager for NIKKE"
authors = ["sinkaroid"]
edition = "2024"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
winres = "0.1"

[dependencies]
tauri = { version = "2.2", features = ["tray-icon"] }
tauri-plugin-dialog = "2.2"
tauri-plugin-notification = "2.2"
tauri-plugin-store = "2.2"
tauri-plugin-opener = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
discord-rich-presence = "0.2"
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Com",
    "Win32_System_Wmi",
    "Win32_System_LibraryLoader",
] }

[lib]
name = "nikkepwned_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
