use std::sync::atomic::{AtomicBool, AtomicPtr, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

#[cfg(windows)]
use windows::Win32::Foundation::{LPARAM, LRESULT, WPARAM};
#[cfg(windows)]
use windows::Win32::System::LibraryLoader::GetModuleHandleW;
#[cfg(windows)]
use windows::Win32::System::Threading::{
    GetCurrentProcess, SetPriorityClass, HIGH_PRIORITY_CLASS, NORMAL_PRIORITY_CLASS,
};
#[cfg(windows)]
use windows::Win32::UI::Input::KeyboardAndMouse::{
    SendInput, INPUT, INPUT_0, INPUT_KEYBOARD, KEYBDINPUT, KEYEVENTF_KEYUP,
    KEYEVENTF_SCANCODE, MapVirtualKeyW, MAPVK_VK_TO_VSC, VIRTUAL_KEY,
};
#[cfg(windows)]
use windows::Win32::UI::WindowsAndMessaging::{
    CallNextHookEx, GetMessageW, PostThreadMessageW, SetWindowsHookExW, UnhookWindowsHookEx,
    HHOOK, KBDLLHOOKSTRUCT, MSG, WH_KEYBOARD_LL, WM_KEYDOWN, WM_KEYUP, WM_QUIT,
    WM_SYSKEYDOWN, WM_SYSKEYUP,
};

/// Maximum number of configurable BurstBonk key slots.
const MAX_KEYS: usize = 5;

/// Interval between each key send in milliseconds (atomic, configurable, default 3ms).
static SPAM_INTERVAL_MS: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(3);

/// Whether humanized random delay jitter (0.3xxx ms - 0.9xxx ms) is enabled.
static HUMANIZED: AtomicBool = AtomicBool::new(false);

/// Magic identifier placed in dwExtraInfo to identify our own synthetic keystrokes.
const BURSTBONK_MAGIC: usize = 0x424F4E4B; // "BONK"

/// VK_F12 for emergency exit / turn off (matching AHK's F12::ExitApp).
const VK_F12: u16 = 0x7B;

#[cfg(windows)]
#[link(name = "winmm")]
unsafe extern "system" {
    fn timeBeginPeriod(u_period: u32) -> u32;
    fn timeEndPeriod(u_period: u32) -> u32;
}

// ───────────────────────────── Global Atomic State ──────────────────────────

/// Per-key flags: true = physical key is held down.
static KEY_ACTIVE: [AtomicBool; MAX_KEYS] = [
    AtomicBool::new(false),
    AtomicBool::new(false),
    AtomicBool::new(false),
    AtomicBool::new(false),
    AtomicBool::new(false),
];

/// Per-key flags: true = a spammer thread is already running for this slot.
static SPAM_RUNNING: [AtomicBool; MAX_KEYS] = [
    AtomicBool::new(false),
    AtomicBool::new(false),
    AtomicBool::new(false),
    AtomicBool::new(false),
    AtomicBool::new(false),
];

/// Virtual key codes currently being tracked (set by `start`, read by the hook lock-free).
static TRACKED_VKS: [std::sync::atomic::AtomicU16; MAX_KEYS] = [
    std::sync::atomic::AtomicU16::new(0),
    std::sync::atomic::AtomicU16::new(0),
    std::sync::atomic::AtomicU16::new(0),
    std::sync::atomic::AtomicU16::new(0),
    std::sync::atomic::AtomicU16::new(0),
];

/// The installed hook handle.
static HOOK_HANDLE: AtomicPtr<std::ffi::c_void> = AtomicPtr::new(std::ptr::null_mut());

/// Thread ID of the message-pump thread (needed for posting WM_QUIT).
static HOOK_THREAD_ID: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(0);

/// Master on/off flag — indicates whether the BurstBonk system is active.
static BURSTBONK_ACTIVE: AtomicBool = AtomicBool::new(false);

// ──────────────────────────── Hook Callback ─────────────────────────────────

/// Low-level keyboard hook procedure.
///
/// Filters out synthetic inputs generated by SendInput (LLKHF_INJECTED or BURSTBONK_MAGIC).
/// For physical tracked keys:
/// - WM_KEYDOWN sets KEY_ACTIVE = true and spawns spammer thread.
/// - WM_KEYUP sets KEY_ACTIVE = false, terminating spammer thread.
/// - Returns LRESULT(1) to swallow physical key, matching AHK's `*a::` behavior.
#[cfg(windows)]
unsafe extern "system" fn ll_keyboard_proc(
    n_code: i32,
    w_param: WPARAM,
    l_param: LPARAM,
) -> LRESULT {
    if n_code >= 0 {
        let kb = unsafe { &*(l_param.0 as *const KBDLLHOOKSTRUCT) };

        // CRITICAL: Ignore ALL injected keystrokes (generated by SendInput).
        // LLKHF_INJECTED is bit 0 of flags. We also check our magic extra info.
        let is_injected = (kb.flags.0 & 1) != 0 || kb.dwExtraInfo == BURSTBONK_MAGIC;
        if is_injected {
            return unsafe {
                CallNextHookEx(HHOOK(HOOK_HANDLE.load(Ordering::SeqCst)), n_code, w_param, l_param)
            };
        }

        let vk = kb.vkCode as u16;
        let msg = w_param.0 as u32;

        // F12: Emergency stop (matching F12::ExitApp in AHK).
        if vk == VK_F12 && (msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN) {
            stop_internal();
            return LRESULT(1);
        }

        if !BURSTBONK_ACTIVE.load(Ordering::SeqCst) {
            return unsafe {
                CallNextHookEx(HHOOK(HOOK_HANDLE.load(Ordering::SeqCst)), n_code, w_param, l_param)
            };
        }

        // Look up the VK in our tracked list lock-free.
        for (idx, slot) in TRACKED_VKS.iter().enumerate() {
            let tvk = slot.load(Ordering::Relaxed);
            if tvk != 0 && tvk == vk {
                match msg {
                    WM_KEYDOWN | WM_SYSKEYDOWN => {
                        KEY_ACTIVE[idx].store(true, Ordering::SeqCst);
                        // Spawn a spammer thread if not already running.
                        if !SPAM_RUNNING[idx].load(Ordering::SeqCst) {
                            SPAM_RUNNING[idx].store(true, Ordering::SeqCst);
                            let scan = unsafe { MapVirtualKeyW(vk as u32, MAPVK_VK_TO_VSC) as u16 };
                            thread::spawn(move || {
                                spammer_loop(idx, vk, scan);
                            });
                        }
                        // Swallow the physical keydown so the game only receives our SendInput stream
                        return LRESULT(1);
                    }
                    WM_KEYUP | WM_SYSKEYUP => {
                        KEY_ACTIVE[idx].store(false, Ordering::SeqCst);
                        // Swallow the physical keyup
                        return LRESULT(1);
                    }
                    _ => {}
                }
                break;
            }
        }
    }

    unsafe { CallNextHookEx(HHOOK(HOOK_HANDLE.load(Ordering::SeqCst)), n_code, w_param, l_param) }
}

// ──────────────────────────── Spammer Loop ──────────────────────────────────

/// Returns a random delay between 300 and 999 microseconds (0.3xxx ms to 0.9xxx ms).
fn get_humanized_jitter_micros() -> u64 {
    use std::cell::Cell;
    thread_local! {
        static RNG: Cell<u64> = Cell::new({
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .subsec_nanos() as u64;
            nanos ^ 0x517CC1B727220A95
        });
    }

    RNG.with(|rng| {
        let mut x = rng.get();
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        rng.set(x);
        // 300 to 999 microseconds (0.3xxx ms - 0.9xxx ms)
        300 + (x % 700)
    })
}

/// Continuously sends key-down / key-up via `SendInput` every `SPAM_INTERVAL_MS` ms
/// (with optional humanized jitter) as long as user physically holds key down.
#[cfg(windows)]
fn spammer_loop(idx: usize, vk: u16, scan: u16) {
    while KEY_ACTIVE[idx].load(Ordering::SeqCst) && BURSTBONK_ACTIVE.load(Ordering::SeqCst) {
        send_scan_key(scan, vk);
        let base_interval = SPAM_INTERVAL_MS.load(Ordering::Relaxed).max(1);
        let delay = if HUMANIZED.load(Ordering::Relaxed) {
            let jitter_micros = get_humanized_jitter_micros();
            Duration::from_micros(base_interval * 1000 + jitter_micros)
        } else {
            Duration::from_millis(base_interval)
        };
        thread::sleep(delay);
    }
    SPAM_RUNNING[idx].store(false, Ordering::SeqCst);
}

/// Sends a single key-down + key-up via scancode (modifier-transparent,
/// equivalent to AHK's `{Blind}` + `SendInput`).
#[cfg(windows)]
fn send_scan_key(scan: u16, vk: u16) {
    let inputs = [
        INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(vk),
                    wScan: scan,
                    dwFlags: KEYEVENTF_SCANCODE,
                    time: 0,
                    dwExtraInfo: BURSTBONK_MAGIC,
                },
            },
        },
        INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(vk),
                    wScan: scan,
                    dwFlags: KEYEVENTF_SCANCODE | KEYEVENTF_KEYUP,
                    time: 0,
                    dwExtraInfo: BURSTBONK_MAGIC,
                },
            },
        },
    ];

    unsafe {
        SendInput(&inputs, std::mem::size_of::<INPUT>() as i32);
    }
}

// ──────────────────────────── Public API ────────────────────────────────────

/// Resolves a single-character key name (e.g. "A", "S", "1", "F") into a
/// Windows virtual-key code.
pub fn key_name_to_vk(name: &str) -> Option<u16> {
    let ch = name.trim().to_uppercase();
    if ch.len() != 1 {
        return None;
    }
    let c = ch.chars().next()?;
    match c {
        'A'..='Z' => Some(c as u16),          // VK_A (0x41) .. VK_Z (0x5A)
        '0'..='9' => Some(c as u16),          // VK_0 (0x30) .. VK_9 (0x39)
        _ => None,
    }
}

/// Holds the handle to a running BurstBonk session.
pub struct BurstBonkHandle {
    _active: Arc<AtomicBool>,
}

impl Drop for BurstBonkHandle {
    fn drop(&mut self) {
        stop_internal();
    }
}

/// Start the BurstBonk system.
///
/// `keys` is a list of single-character key names, e.g. `["A", "S", "D", "F", "G"]`.
/// `interval_ms` is the spam rate in milliseconds (default: 3ms).
/// `humanized` enables random 0.3xxx ms - 0.9xxx ms delay jitter per keypress.
/// Returns a handle that will stop the system when dropped, or an error if the
/// system is already running or keys are invalid.
#[cfg(windows)]
pub fn start(keys: &[String], interval_ms: u64, humanized: bool) -> Result<BurstBonkHandle, String> {
    if BURSTBONK_ACTIVE.load(Ordering::SeqCst) {
        return Err("BurstBonk is already running".into());
    }

    if keys.is_empty() || keys.len() > MAX_KEYS {
        return Err(format!("Provide 1–{MAX_KEYS} keys"));
    }

    // Set the spam interval and humanized jitter mode.
    SPAM_INTERVAL_MS.store(interval_ms.max(1), Ordering::SeqCst);
    HUMANIZED.store(humanized, Ordering::SeqCst);

    // Resolve key names → VK codes.
    let mut vks = [0u16; MAX_KEYS];
    for (i, name) in keys.iter().enumerate() {
        vks[i] = key_name_to_vk(name)
            .ok_or_else(|| format!("Invalid key name: '{name}' — use A–Z or 0–9"))?;
    }

    // Store tracked VKs for the hook callback lock-free.
    for i in 0..MAX_KEYS {
        TRACKED_VKS[i].store(vks[i], Ordering::SeqCst);
    }

    // Reset all flags.
    for i in 0..MAX_KEYS {
        KEY_ACTIVE[i].store(false, Ordering::SeqCst);
        SPAM_RUNNING[i].store(false, Ordering::SeqCst);
    }

    BURSTBONK_ACTIVE.store(true, Ordering::SeqCst);

    // Set process priority to HIGH and enable 1ms high-resolution timer.
    unsafe {
        let _ = SetPriorityClass(GetCurrentProcess(), HIGH_PRIORITY_CLASS);
        timeBeginPeriod(1);
    }

    // Spawn the hook + message-pump thread.
    thread::spawn(|| {
        unsafe {
            // Store thread ID so we can post WM_QUIT from another thread.
            let thread_id = windows::Win32::System::Threading::GetCurrentThreadId();
            HOOK_THREAD_ID.store(thread_id, Ordering::SeqCst);

            let h_instance = GetModuleHandleW(None).unwrap_or_default();

            let hook = SetWindowsHookExW(WH_KEYBOARD_LL, Some(ll_keyboard_proc), h_instance, 0)
                .map_err(|e| format!("SetWindowsHookExW failed: {e}"))
                .unwrap();

            HOOK_HANDLE.store(hook.0, Ordering::SeqCst);

            // Message pump — required for the low-level hook to receive callbacks.
            let mut msg = MSG::default();
            while GetMessageW(&mut msg, None, 0, 0).as_bool() {
                // No dispatch needed — we only care about keeping the pump alive.
            }

            // Cleanup after WM_QUIT.
            let _ = UnhookWindowsHookEx(hook);
            HOOK_HANDLE.store(std::ptr::null_mut(), Ordering::SeqCst);
        }
    });

    Ok(BurstBonkHandle {
        _active: Arc::new(AtomicBool::new(true)),
    })
}

/// Stop the BurstBonk system.
#[cfg(windows)]
fn stop_internal() {
    if !BURSTBONK_ACTIVE.load(Ordering::SeqCst) {
        return;
    }

    BURSTBONK_ACTIVE.store(false, Ordering::SeqCst);

    // Signal all spammer threads to exit.
    for i in 0..MAX_KEYS {
        KEY_ACTIVE[i].store(false, Ordering::SeqCst);
    }

    // Post WM_QUIT to the hook thread's message pump.
    let thread_id = HOOK_THREAD_ID.load(Ordering::SeqCst);
    if thread_id != 0 {
        unsafe {
            let _ = PostThreadMessageW(thread_id, WM_QUIT, WPARAM(0), LPARAM(0));
        }
        HOOK_THREAD_ID.store(0, Ordering::SeqCst);
    }

    // Restore normal process priority and timer resolution.
    unsafe {
        timeEndPeriod(1);
        let _ = SetPriorityClass(GetCurrentProcess(), NORMAL_PRIORITY_CLASS);
    }
}

/// Public stop function callable from Tauri commands.
pub fn stop() {
    #[cfg(windows)]
    stop_internal();
}

/// Returns whether the BurstBonk system is currently active.
pub fn is_active() -> bool {
    BURSTBONK_ACTIVE.load(Ordering::SeqCst)
}
